# Base configs
baseurl: "http://kritarth.artiosys.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Baby K Urff Ladoo Bhai"
subtitle: "Kritarth Garg"
author: ""
header:
 title: "Baby K Urff Ladoo Bhai"
 subtitle: "Kritarth Garg"
footer:
 name: "Hey there, my name is Kritarth Garg"
 bio: "Currently giving sleepless nights & endless love to mumma @agarwal.radhika25 and dadda @satyarth.garg47"
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/baby_kritarth/"